### ISSUE TITLE
Leah's "Report an issue" form is not showing properly

### ISSUE THREAD

**Issue by hazeljpw** [Benstamous/Project_Flash#2]
![image](https://github.com/Benstamous/Project_Flash/assets/133815478/09c241ef-bad1-4718-92c9-b9072787b6aa)

**Comment by hazeljpw** [comment]
The issue is due to the styling made for .row and .row-content. I comment it out to exclude this styling and it resolved the issue.
![image](https://github.com/Benstamous/Project_Flash/assets/133815478/93253f14-96c9-4e90-b019-8e294d17422f)

**Comment by leahkatherine** [comment]
Thank you so much!
