### ISSUE TITLE
Converting styling css issue with about.html 

### ISSUE THREAD

**Issue by leahkatherine** [Benstamous/Project_Flash#9]
I created a pull request for you all to be able to view / make a branch from my code, originating from the branch "leah". This way we can check all resolutions, and comments,  AND we can actually view whether or not your resolution to this will break the code before we merge to main, which can be found on the actual pull request. 
After my assigned role in getting our styles-cv.css & about.html to reflect tour team decision, I ran into an a problem where I cannot locate why the footer nav links are underlined like a hyper link. I've brought everything from our css over to Cassandras and I'm at a  loss for this styling behavior. I have pushed this to main for 
More than one person can work on this issue so I will assign it to everyone. You can look to see if anyone have already started on the issue, by looking under branches to see if a branch has been made already.  ========> look to your right over here ===> 
When your ready or you think you've solved this issue, i am 99.99% sure committing your changed to the branch issue creates another pull request or atleast a request for me to view. 

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by sunnyeyles** [comment]
Add this to about.html:
`    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>`

**Comment by leahkatherine** [comment]
Wow thank you so much for chiming in! I so appreciate it.
